import type { NaturalEntry, StoredSample } from "@/types/domain";

// Descargas
export const initialNaturalEntries: NaturalEntry[] = [
  {
    id: "ING-5001",
    entryDate: "2026-03-27",
    truckPlate: "AE123ZX",
    client: "Molino Andino",
    supplier: "Finca El Alba",
    product: "Poroto alubia",
    processCode: "PROC-A3",
    grossKg: 30500,
    tareKg: 9800,
    netKg: 20700,
    withAnalysis: true,
    analysisCode: "ANA-1002",
    observations: "Ingreso dentro de especificacion.",
    packagingMovements: [
      {
        id: "PKG-5001-1",
        movementType: "alta",
        packagingType: "BOLSON DE 1000 KG",
        packagingCondition: "USADO",
        quantity: 20,
      },
    ],
    analysisSummary: {
      humidityPct: 11.8,
      brokenPct: 1.6,
      foreignMatterPct: 0.4,
      notes: "Ingreso dentro de especificacion.",
    },
  },
  {
    id: "ING-5002",
    entryDate: "2026-03-29",
    truckPlate: "AF552TY",
    client: "Agro Pacifico",
    supplier: "Campo Norte",
    product: "Poroto negro",
    processCode: "PROC-L1",
    grossKg: 31800,
    tareKg: 9950,
    netKg: 21850,
    withAnalysis: false,
    analysisCode: "",
    observations: "Descarga directa a playa sin analisis asociado.",
    packagingMovements: [
      {
        id: "PKG-5002-1",
        movementType: "alta",
        packagingType: "BOLSA 50 KG",
        packagingCondition: "NUEVO",
        quantity: 110,
      },
    ],
  },
  {
    id: "ING-5003",
    entryDate: "2026-03-31",
    truckPlate: "AC880LM",
    client: "Exportadora Sur",
    supplier: "Productores Unidos",
    product: "Poroto cranberry",
    processCode: "PROC-CR1",
    grossKg: 30120,
    tareKg: 9600,
    netKg: 20520,
    withAnalysis: true,
    analysisCode: "ANA-1004",
    observations: "Lote con seguimiento especial previo a almacenamiento.",
    packagingMovements: [
      {
        id: "PKG-5003-1",
        movementType: "alta",
        packagingType: "BOLSON DE 1000 KG",
        packagingCondition: "USADO",
        quantity: 18,
      },
      {
        id: "PKG-5003-2",
        movementType: "baja",
        packagingType: "BOLSA 25 KG",
        packagingCondition: "USADO",
        quantity: 6,
      },
    ],
    analysisSummary: {
      humidityPct: 12.4,
      brokenPct: 2.1,
      foreignMatterPct: 0.8,
      notes: "Revisar limpieza previa al almacenamiento.",
    },
  },
  {
    id: "ING-5004",
    entryDate: "2026-04-01",
    truckPlate: "AG441BN",
    client: "Molino Andino",
    supplier: "Los Ceibos",
    product: "Poroto colorado",
    processCode: "PROC-C2",
    grossKg: 28950,
    tareKg: 9450,
    netKg: 19500,
    withAnalysis: true,
    analysisCode: "ANA-1003",
    observations: "Recepcion estable y descarga sin desvio operativo.",
    packagingMovements: [
      {
        id: "PKG-5004-1",
        movementType: "alta",
        packagingType: "BOLSON DE 1000 KG",
        packagingCondition: "USADO",
        quantity: 19,
      },
    ],
    analysisSummary: {
      humidityPct: 11.3,
      brokenPct: 1.2,
      foreignMatterPct: 0.3,
      notes: "Buen comportamiento de descarga.",
    },
  },
];

// Muestras
export const initialStoredSamples: StoredSample[] = [
  {
    id: "SMP-9001",
    storedAt: "2026-03-20",
    sampleCode: "MS-24-001",
    client: "Exportadora Sur",
    supplier: "FINCA SUR 1",
    product: "Poroto negro",
    processCode: "PROC-L1",
    relatedAnalysisId: "ANA-1001",
    warehouseZone: "Zona A",
    shelf: "A-03",
    gramajeHundredths: 230,
    quantityKg: 12,
    retentionUntil: "2026-05-20",
    status: "Activa",
    notes: "Muestra patron de referencia comercial.",
  },
  {
    id: "SMP-9002",
    storedAt: "2026-03-25",
    sampleCode: "MS-24-014",
    client: "Molino Andino",
    supplier: "CAMPO EL OASIS",
    product: "Poroto alubia",
    processCode: "PROC-A3",
    relatedAnalysisId: "ANA-1002",
    warehouseZone: "Zona B",
    shelf: "B-11",
    gramajeHundredths: 200,
    quantityKg: 8,
    retentionUntil: "2026-04-18",
    status: "Activa",
    notes: "Se conserva para reclamo potencial del cliente.",
  },
  {
    id: "SMP-9003",
    storedAt: "2026-03-12",
    sampleCode: "MS-24-020",
    client: "Agro Pacifico",
    supplier: "LOTE PACIFICO",
    product: "Poroto colorado",
    processCode: "PROC-C2",
    relatedAnalysisId: "ANA-1003",
    warehouseZone: "Zona C",
    shelf: "C-02",
    gramajeHundredths: 210,
    quantityKg: 10,
    retentionUntil: "2026-04-05",
    status: "Activa",
    notes: "Control cruzado con laboratorio externo.",
  },
  {
    id: "SMP-9004",
    storedAt: "2026-02-28",
    sampleCode: "MS-24-027",
    client: "Exportadora Sur",
    supplier: "FINCA NORTE",
    product: "Poroto cranberry",
    processCode: "PROC-CR1",
    relatedAnalysisId: "ANA-1004",
    warehouseZone: "Zona A",
    shelf: "A-07",
    gramajeHundredths: 185,
    quantityKg: 6,
    retentionUntil: "2026-03-28",
    status: "Vencida",
    notes: "Pendiente de disposicion final.",
  },
];
