import type { DefectAnalysis, NaturalEntry, StoredSample } from "@/types/domain";

export const initialDefectAnalyses: DefectAnalysis[] = [
  {
    id: "ANA-1001",
    analysisDate: "2026-03-28",
    client: "Exportadora Sur",
    product: "Poroto negro",
    processCode: "PROC-L1",
    lotCode: "L-2238",
    operator: "Paula Gimenez",
    totalUnitsInspected: 480,
    defects: [
      { id: "d1", name: "Partido", count: 16 },
      { id: "d2", name: "Materia extraña", count: 5 },
      { id: "d3", name: "Manchado", count: 9 },
    ],
    observations: "Lote estable, con desvío leve en clasificación final.",
  },
  {
    id: "ANA-1002",
    analysisDate: "2026-03-29",
    client: "Molino Andino",
    product: "Poroto alubia",
    processCode: "PROC-A3",
    lotCode: "L-2241",
    operator: "Leonardo Sosa",
    totalUnitsInspected: 520,
    defects: [
      { id: "d4", name: "Picado", count: 11 },
      { id: "d5", name: "Partido", count: 7 },
    ],
    observations: "Necesita revisar zaranda de ingreso por presencia de picado.",
  },
  {
    id: "ANA-1003",
    analysisDate: "2026-03-30",
    client: "Agro Pacífico",
    product: "Poroto colorado",
    processCode: "PROC-C2",
    lotCode: "L-2249",
    operator: "Micaela Vera",
    totalUnitsInspected: 410,
    defects: [
      { id: "d6", name: "Partido", count: 13 },
      { id: "d7", name: "Descolorido", count: 6 },
      { id: "d8", name: "Materia extraña", count: 4 },
    ],
    observations: "Desvío asociado a mezcla de calibres en pre-limpieza.",
  },
  {
    id: "ANA-1004",
    analysisDate: "2026-04-01",
    client: "Exportadora Sur",
    product: "Poroto cranberry",
    processCode: "PROC-CR1",
    lotCode: "L-2254",
    operator: "Paula Gimenez",
    totalUnitsInspected: 450,
    defects: [
      { id: "d9", name: "Manchado", count: 14 },
      { id: "d10", name: "Partido", count: 8 },
    ],
    observations: "Recomendado ajustar humedad antes de embolsado.",
  },
];

export const initialNaturalEntries: NaturalEntry[] = [
  {
    id: "ING-5001",
    entryDate: "2026-03-27",
    truckPlate: "AE123ZX",
    client: "Molino Andino",
    supplier: "Finca El Alba",
    product: "Poroto alubia",
    processCode: "PROC-A3",
    grossKg: 30500,
    tareKg: 9800,
    netKg: 20700,
    withAnalysis: true,
    analysisSummary: {
      humidityPct: 11.8,
      brokenPct: 1.6,
      foreignMatterPct: 0.4,
      notes: "Ingreso dentro de especificación.",
    },
  },
  {
    id: "ING-5002",
    entryDate: "2026-03-29",
    truckPlate: "AF552TY",
    client: "Agro Pacífico",
    supplier: "Campo Norte",
    product: "Poroto negro",
    processCode: "PROC-L1",
    grossKg: 31800,
    tareKg: 9950,
    netKg: 21850,
    withAnalysis: false,
  },
  {
    id: "ING-5003",
    entryDate: "2026-03-31",
    truckPlate: "AC880LM",
    client: "Exportadora Sur",
    supplier: "Productores Unidos",
    product: "Poroto cranberry",
    processCode: "PROC-CR1",
    grossKg: 30120,
    tareKg: 9600,
    netKg: 20520,
    withAnalysis: true,
    analysisSummary: {
      humidityPct: 12.4,
      brokenPct: 2.1,
      foreignMatterPct: 0.8,
      notes: "Revisar limpieza previa al almacenamiento.",
    },
  },
  {
    id: "ING-5004",
    entryDate: "2026-04-01",
    truckPlate: "AG441BN",
    client: "Molino Andino",
    supplier: "Los Ceibos",
    product: "Poroto colorado",
    processCode: "PROC-C2",
    grossKg: 28950,
    tareKg: 9450,
    netKg: 19500,
    withAnalysis: true,
    analysisSummary: {
      humidityPct: 11.3,
      brokenPct: 1.2,
      foreignMatterPct: 0.3,
      notes: "Buen comportamiento de descarga.",
    },
  },
];

export const initialStoredSamples: StoredSample[] = [
  {
    id: "SMP-9001",
    storedAt: "2026-03-20",
    sampleCode: "MS-24-001",
    client: "Exportadora Sur",
    product: "Poroto negro",
    processCode: "PROC-L1",
    relatedAnalysisId: "ANA-1001",
    warehouseZone: "Zona A",
    shelf: "A-03",
    quantityKg: 12,
    retentionUntil: "2026-05-20",
    status: "Activa",
    notes: "Muestra patrón de referencia comercial.",
  },
  {
    id: "SMP-9002",
    storedAt: "2026-03-25",
    sampleCode: "MS-24-014",
    client: "Molino Andino",
    product: "Poroto alubia",
    processCode: "PROC-A3",
    relatedAnalysisId: "ANA-1002",
    warehouseZone: "Zona B",
    shelf: "B-11",
    quantityKg: 8,
    retentionUntil: "2026-04-18",
    status: "Activa",
    notes: "Se conserva para reclamo potencial del cliente.",
  },
  {
    id: "SMP-9003",
    storedAt: "2026-03-12",
    sampleCode: "MS-24-020",
    client: "Agro Pacífico",
    product: "Poroto colorado",
    processCode: "PROC-C2",
    relatedAnalysisId: "ANA-1003",
    warehouseZone: "Zona C",
    shelf: "C-02",
    quantityKg: 10,
    retentionUntil: "2026-04-05",
    status: "Activa",
    notes: "Control cruzado con laboratorio externo.",
  },
  {
    id: "SMP-9004",
    storedAt: "2026-02-28",
    sampleCode: "MS-24-027",
    client: "Exportadora Sur",
    product: "Poroto cranberry",
    processCode: "PROC-CR1",
    relatedAnalysisId: "ANA-1004",
    warehouseZone: "Zona A",
    shelf: "A-07",
    quantityKg: 6,
    retentionUntil: "2026-03-28",
    status: "Vencida",
    notes: "Pendiente de disposición final.",
  },
];
